// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENCbi4H_CjJa4sM5y4TBgtY19JnQJdhc',
    appId: '1:157761554244:web:90c33a6169d0776c3e3911',
    messagingSenderId: '157761554244',
    projectId: 'voxify-bb2fb',
    authDomain: 'voxify-bb2fb.firebaseapp.com',
    storageBucket: 'voxify-bb2fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRpy2JzT9MdeqBoYT0eV4E8QKcdx-MLM',
    appId: '1:157761554244:android:79623005ea7c01933e3911',
    messagingSenderId: '157761554244',
    projectId: 'voxify-bb2fb',
    storageBucket: 'voxify-bb2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXD3yqlRgy9eR9sP4qkk4uDEq4U3GJec',
    appId: '1:157761554244:ios:e66f0b7c2081b56a3e3911',
    messagingSenderId: '157761554244',
    projectId: 'voxify-bb2fb',
    storageBucket: 'voxify-bb2fb.appspot.com',
    iosBundleId: 'com.example.verbalize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFXD3yqlRgy9eR9sP4qkk4uDEq4U3GJec',
    appId: '1:157761554244:ios:e66f0b7c2081b56a3e3911',
    messagingSenderId: '157761554244',
    projectId: 'voxify-bb2fb',
    storageBucket: 'voxify-bb2fb.appspot.com',
    iosBundleId: 'com.example.verbalize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAENCbi4H_CjJa4sM5y4TBgtY19JnQJdhc',
    appId: '1:157761554244:web:8dc4d3baff3ee06b3e3911',
    messagingSenderId: '157761554244',
    projectId: 'voxify-bb2fb',
    authDomain: 'voxify-bb2fb.firebaseapp.com',
    storageBucket: 'voxify-bb2fb.appspot.com',
  );
}
